#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR "/CMS.API"
COPY ["CMS.API/CMS.API.csproj", "CMS.API/"]
RUN dotnet restore "CMS.API/CMS.API.csproj"
COPY . .
WORKDIR "/CMS.API/CMS.API"
RUN dotnet build "CMS.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CMS.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR "/CMS.API/CMS.API"
COPY --from=publish /app/publish .

CMD ASPNETCORE_URLS=http://*:$PORT dotnet CMS.API.dll
#ENTRYPOINT ["dotnet", "CMS.API.dll"]